name: Nightly CVAT ETL

on:
  schedule:
    - cron: "0 1 * * *"   # runs every day at 01:00 UTC; change if you want
  workflow_dispatch:       # lets you run it manually from the Actions tab

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Write your Google service account JSON (from a GitHub Secret) to a file
      - name: Create Google creds file
        run: |
          echo '${{ secrets.GOOGLE_SA_JSON }}' > credentials.json

      # Run your main CVAT script (fast/nightly: no heavy annotation fetch)
      - name: Run CVAT ETL (fast nightly)
        env:
          CVAT_BASE_URL: ${{ secrets.CVAT_BASE_URL }}
          CVAT_API_TOKEN: ${{ secrets.CVAT_API_TOKEN }}
          CVAT_ORG_HEADER: ${{ secrets.CVAT_ORG_HEADER }}
          GSHEET_URL_CVAT: ${{ secrets.GSHEET_URL_CVAT }}
          ETL_FETCH_ANNOTATIONS: "0"
          ETL_MAX_PROJECTS: "0"
          ETL_MAX_TASKS_PER_PROJ: "0"
          ETL_MAX_JOBS_PER_TASK: "0"
        run: |
          python cvat_to_metabase_full.py 

      # - name: Run CVAT ETL
      #   env:
      #     CVAT_BASE_URL: ${{ secrets.CVAT_BASE_URL }}
      #     CVAT_API_TOKEN: ${{ secrets.CVAT_API_TOKEN }}
      #     CVAT_ORG_HEADER: ${{ secrets.CVAT_ORG_HEADER }}   # optional
      #     GSHEET_URL_CVAT: ${{ secrets.GSHEET_URL_CVAT }}   # Google Sheet URL where tabs live
      #     ETL_FETCH_ANNOTATIONS: "0"   # keep nightly fast
      #     ETL_MAX_PROJECTS: "0"
      #     ETL_MAX_TASKS_PER_PROJ: "0"
      #     ETL_MAX_JOBS_PER_TASK: "0"
      #   run: |
      #     python cvat_to_metabase_full.py
